#ifndef DATASTORAGEABSTRACTION_GLOBAL_H
#define DATASTORAGEABSTRACTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATASTORAGEABSTRACTION_LIBRARY)
#  define DATASTORAGEABSTRACTION_EXPORT Q_DECL_EXPORT
#else
#  define DATASTORAGEABSTRACTION_EXPORT Q_DECL_IMPORT
#endif

#endif // DATASTORAGEABSTRACTION_GLOBAL_H
